spring.application.name=persona

# Base de datos local en memoria para que el proyecto pueda arrancar sin MySQL instalado
spring.datasource.url=jdbc:h2:mem:db_persona;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Variable de entorno
server.port=9000
